### ISSUE TITLE
Please continue effort on this. It's amazing and I love it.

### ISSUE THREAD

**Issue by NuptupTDOW** [CDeenen/MaterialPlane#10]
I have genuinely been trying to figure out how to do this myself and here you are, doing exactly that. It's amazing and crunchy and unique and I'd love to see it pushed more. I definitely would be more interested in just paying one lump sum and having the full kit mailed to me, but I understand your hesitation. Just, know that I like many others could definitely use this to great effect!

**Comment by CDeenen** [comment]
While this github hasn't received an update in a very long time, the module is still actively being worked on. I've been working on the new hardware, and developing hardware can, unfortunately, take some time, especially since I plan on selling it. 
I post regular updates on my Discord server, so feel free to join that if you like: https://discord.gg/3hd4G6TkmA
