### ISSUE TITLE
Failing to Upload

### ISSUE THREAD

**Issue by bpbarwick** [CDeenen/MaterialPlane#16]
I am attempting to upload to a TinyS3 using an esp32 Dev Kit and esp version 1.0.6 as stated in this [other issue](https://github.com/MaterialFoundry/MaterialPlane/issues/15). Arduino IDE is able to compile, but fails to upload with the following error message. This may very well be something I am doing wrong, but I have followed the Material Foundry instructions step by step on two different computers now with the same results.

```
Arduino: 1.8.19 (Windows 10), Board: "ESP32 Dev Module, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, None"

Sketch uses 1060246 bytes (80%) of program storage space. Maximum is 1310720 bytes.

Global variables use 51568 bytes (15%) of dynamic memory, leaving 276112 bytes for local variables. Maximum is 327680 bytes.

C:\Users\bpbar\AppData\Local\Arduino15\packages\esp32\tools\esptool_py\3.0.0/esptool.exe --chip esp32 --port COM5 --baud 921600 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 80m --flash_size detect 0xe000 C:\Users\bpbar\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6/tools/partitions/boot_app0.bin 0x1000 C:\Users\bpbar\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6/tools/sdk/bin/bootloader_qio_80m.bin 0x10000 C:\Users\bpbar\AppData\Local\Temp\arduino_build_888661/Sensor.ino.bin 0x8000 C:\Users\bpbar\AppData\Local\Temp\arduino_build_888661/Sensor.ino.partitions.bin 

esptool.py v3.1-dev

Serial port COM5

Connecting...

Traceback (most recent call last):

  File "esptool.py", line 4423, in <module>

  File "esptool.py", line 4416, in _main

  File "esptool.py", line 3966, in main

  File "esptool.py", line 120, in get_default_connected_device

  File "esptool.py", line 567, in connect

  File "esptool.py", line 539, in _connect_attempt

  File "esptool.py", line 478, in sync

  File "esptool.py", line 414, in command

  File "esptool.py", line 377, in write

  File "site-packages\serial\serialwin32.py", line 323, in write

serial.serialutil.SerialTimeoutException: Write timeout

Failed to execute script esptool

An error occurred while uploading the sketch



This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
```

**Comment by CDeenen** [comment]
Hey, as I mentioned in the other issue, the current DIY firmware does not work on an esp32-s3 (which the TinyS3 is). Simply setting the board to an esp32 devkit won't work, because you don't have an esp32 devkit connected and during the firmware upload the software notices this.
What the other person did was buy an esp32 devkit. You could do the same, or wait until I have made the latest firmware version (currently only for the production sensor) available for the DIY sensor.
If you decide to buy another board, please double check that it is actually an esp32 board, and not some variant (such as the esp32-s2, esp32-s3, esp32-c2, etc). You might have to look at the product details, not just the product name. For example, the Arduino Nano Esp32 is actually an esp32-s3.

**Comment by bpbarwick** [comment]
Thanks for the explanation and sorry for my stupidity! I guess I had just scanned over that other issue and missed that key point. I appreciate your timely response.
