### ISSUE TITLE
Contact info?

### ISSUE THREAD

**Issue by Arlllen** [CDeenen/MaterialPlane#5]
Hi man!
Really love your idea, and that's a blessing to have such a module and technology . But I can't find any info on how to contact you.
I'm not tech savvy guy, but I really want that thing to be a part of my table.
If that's possible I would like to buy the product or the parts to assemble it without cutting wires or anything like that
Perhaps 1 camera and 6 bases for minis

My contacts:
Discord: Аклеон#3277

**Comment by CDeenen** [comment]
Hey, thank you for your interest.

My email and discord are at the bottom of the main readme, they're: cdeenen@outlook.com and Cris#6864

I removed your telegram and phone number from the above post, because you might not want them here for all to see.

Currently I do not sell any of the parts, I want to make sure everything works and I have finalized the hardware.
Considering the interest this module has gotten, I'm pretty sure I'll start selling kits soon.

Closing this issue, if you have further questions you now know where to find me :)
