### ISSUE TITLE
Possible New Idea (Suggestion)

### ISSUE THREAD

**Issue by Sonny-Crockett** [CDeenen/MaterialPlane#9]
I have used Go(Baduk) tracking software for many years, following different variations of it. Now its a simpler problem because its just black and white stones, but I think with the advances in technology regard image recognition, something like this could be expanded on for RPG with Video Table Tops. 

Just thinking in basic terms, the Foundry VTT program could have "anchor" images on the corners that would help tell the Webcam where the Grid is. My hope for this as an option would mean easier adoption but I understand it would require more coding. I just wanted to share this idea from my experience.   

http://www.oipaz.net/2016-KSFBS.pdf - Scientific Paper on VideoKifu

![image](https://user-images.githubusercontent.com/39606970/101798037-a6293f00-3ad8-11eb-8f09-aaf36b66dfb0.png)

**Comment by CDeenen** [comment]
Thank you for your suggestion.
The camera used for Material Plane can only detect IR, so the only way to permanently anchor the grid would be to have 4 corner IR LEDs on all the time. This isn't really possible because it'll cause issues when trying to track minis.
What you can do, is only turn on the corner LEDs during a calibration procedure, and as long as the LEDs are always in the same location relative to the grid, you can very quickly calibrate the sensor. You can already do that with Material Plane, using the Multipoint Calibration option.
Thanks for the paper, I'll read through it when I have some more time. There might be stuff in there that's useful for Material Plane.
